### ISSUE TITLE
Flutter 3.11 issue

### ISSUE THREAD

**Issue by fennelhans** [cmdrootaccess/another-flushbar#106]
**Describe the bug**

```
Error: The
argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is
nullable and 'BorderRadiusGeometry' isn't.
```

**To Reproduce**
1. Update to the latest version of Flutter (I'm using the main branch, but it will be released tomorrow, so just wait a day and update)
2. Try to build

**Comment by cmdrootaccess** [comment]
> **Describe the bug**
> 
> 
> 
> ```
> 
> Error: The
> 
> argument type 'BorderRadius?' can't be assigned to the parameter type 'BorderRadiusGeometry' because 'BorderRadius?' is
> 
> nullable and 'BorderRadiusGeometry' isn't.
> 
> ```
> 
> 
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Update to the latest version of Flutter (I'm using the main branch, but it will be released tomorrow, so just wait a day and update)
> 
> 2. Try to build
> 
> 

Good Looking out on this.

**Comment by faheemletitgo** [comment]
please update this to the stable version as well and support flutter 3.10
