### ISSUE TITLE
please fix these issues and update to stable version please

### ISSUE THREAD

**Issue by faheemletitgo** [cmdrootaccess/another-flushbar#107]
Fixing type incompatibility: The error also indicates type incompatibility issues, particularly related to BorderRadius. Check the versions of the packages involved (flushbar, flutter_speed_dial, data_table_2, etc.) and make sure they are compatible with each other. You may need to update some packages or find alternative packages that are compatible.

File-specific issues: If the errors persist, it's possible that there might be specific issues in the files mentioned (get_information_parser.dart, get_router_delegate.dart, flushbar.dart, etc.). Review those files and see if there are any updates, fixes, or alternative packages available for them.

Consult package documentation: Check the documentation of the packages causing the errors (e.g., get, another_flushbar, flutter_speed_dial, data_table_2) for any known issues or updates. Sometimes, package authors provide solutions or workarounds for common errors.

**Comment by cmdrootaccess** [comment]
closing. doesnt follow bug report
