### ISSUE TITLE
isDissmissible doesnt work with "back" button.

### ISSUE THREAD

**Issue by Pepslee** [cmdrootaccess/another-flushbar#14]
I try to use isDissmissible=false, to turn off swiping dissmissible. I want to dissmiss flushbar manually  by a condition (in code).
And  now swiping doesnt dismiss the flushbar, but when I press the native android "back" button, the flushbar is dismissing.
How can I turn off all possible ways to dismiss except of manually call Flushbar().dismiss() ??

**Comment by cmdrootaccess** [comment]
okay noted. i will look into it shortly, and give response

**Comment by robinbonnes** [comment]
Fixed this and proposed a pull-request here: https://github.com/cmdrootaccess/another-flushbar/pull/33

**Comment by cmdrootaccess** [comment]
fixed in another_flushbar: ^1.10.23
