### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by devj3ns** [cmdrootaccess/another-flushbar#2]
It would be really cool if the package migrates to null safety in the next months :)

**Comment by deakjahn** [comment]
I wasn't even aware of the original package being abandoned, just that I started to look for null safety of my regular dependencies. :-) Null safety is more than an enhancement now, it will soon be compulsory moving forward as it reaches the stable branch.

Could we get some info about how this goes, whether you need help to make the shift, whether there is some background info about what happened with the original package?

**Comment by cmdrootaccess** [comment]
it seems the original author of the flushbar stopped developing it. hence i took over. if you want to make a null safety PR you are welcome. 

i will also look into null safety this week and i can make a commit.

**Comment by deakjahn** [comment]
Is he completely unavailable, or just not interested in it any more? Because if you can contact him, it might be better to keep that going. Hopefully nothing serious happened.

**Comment by cmdrootaccess** [comment]
i really dont know just like everyone else on here

**Comment by behnamsattar** [comment]
Flutter 2.0 is out and this needs to happen ASAP.

**Comment by cmdrootaccess** [comment]
will try my best to make it happen today.

**Comment by kw2019ltd** [comment]
> 
> 
> will try my best to make it happen today.

Description

All dependencies are migrated to null safety. So we should migrate this package to null safety.
Resources

https://www.youtube.com/watch?v=eBr5tlumwlg&feature=youtu.be
https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730

**Comment by Vitor-Bukovitz** [comment]
@cmdrootaccess  Thanks! Can't wait for the update!

**Comment by deakjahn** [comment]
Thanks, almost. But the standard procedure calls for marking a breaking change, moving on to version 2.0.0-nullsafety.1. Then publish it so to Pub.dev. It will appear as a prerelase automatically (because of the extra tag in the version), both versions will co-exist automatically until the null safety move is completely over. Also, this will tell anybody looking around on Pub to see whether all their dependencies are already null-safe that your package is.
