### ISSUE TITLE
missing/add borderRadius , it was avaialbe on old plugin flushbar

### ISSUE THREAD

**Issue by kw2019ltd** [cmdrootaccess/another-flushbar#20]
![image](https://user-images.githubusercontent.com/47334522/111901876-3a456380-8a43-11eb-95b2-83d78731f2c6.png)

**Comment by kw2019ltd** [comment]
below     //borderRadius: 8,  was exist in old plugin
Flushbar<bool>(
    flushbarStyle: FlushbarStyle.FLOATING,
    backgroundColor: Colors.red,
    messageText: Text(
      text,
      style: const TextStyle(
          fontSize: 16, fontWeight: FontWeight.bold, color: Colors.white),
    ),
    margin: EdgeInsets.all(8),
    //borderRadius: 8,
    duration: Duration(seconds: duration),
    flushbarPosition: flushbarPosition,
    onTap: (Flushbar flushbar) {
      flushbar.dismiss(true);
    },
    leftBarIndicatorColor:
        SharedPreferencesImpl().isDarkTheme$ ? Colors.white : null,
    isDismissible: true,
    icon: icon,
  ).show(context);

**Comment by cmdrootaccess** [comment]
okay investigating

**Comment by kw2019ltd** [comment]
> 
> 
> okay investigating

sorry closing this issue. its exist in different way
