### ISSUE TITLE
iOS Flushbar does not stay grounded at bottom of screen, even with "FlushbarStyle.GROUNDED". There is blank space where the iOS dismiss bar is located.

### ISSUE THREAD

**Issue by mjacobsca** [cmdrootaccess/another-flushbar#22]
iOS Flushbar does not stay grounded at bottom of screen, even with "FlushbarStyle.GROUNDED". There is blank space where the iOS dismiss bar is located. This only happens when I use "containers" as the widget instead of a Text widget.

NOTE: USING VERSION 1.10.11 BECAUSE WE ARE WAITING ON SOME OTHER PACKAGES TO BECOME NULL SAFE BEFORE UPGRADING OUR DART VERSION.

**Comment by cmdrootaccess** [comment]
will look at

**Comment by mjacobsca** [comment]
Awesome. Here's a preview of what happens.

![image](https://user-images.githubusercontent.com/72184020/114094710-7c5b0b80-9871-11eb-84d8-1caa22092c8a.png)

**Comment by mjacobsca** [comment]
Here's on more. This one is WAY off. It works perfectly on Android.

![flushbar_example_extra_spacing2](https://user-images.githubusercontent.com/72184020/114104407-a6b3c580-987f-11eb-8cf3-542853ed31c1.jpg)

**Comment by mjacobsca** [comment]
Doing some more experimenting. I think what is happening is that the "safe area" (the dismiss bar area) is showing up below the widget as it pops up. I'd rather the widget have the option of grounding into the safe area. I can set the backgroundColor, but it's not great for all of my widgets to have a solid color at the bottom. For now, I'll choose black as the color. But the ideal solution is that FlushbarStyle.GROUNDED attaches the dialog to bottom (or top) of the screen regardless of safe area.

**Comment by mjacobsca** [comment]
Hello again. Not much response here. But what I ended up doing was making the safe area optional like below (it's what i needed for a clean experience - i'll leave it up to the widget to account for the bottom safe zone):

Material(...
   child: widget.flushbarStyle == FlushbarStyle.GROUNDED
            ? _getFlushbar()
            : SafeArea(...)
