### ISSUE TITLE
flushbar hides behind keyboard flutter

### ISSUE THREAD

**Issue by abdulrojak288** [cmdrootaccess/another-flushbar#24]
I have a simple form and always snackbar shows behind keyboard. Any special configuration so I can show my snackbar top of the keyboard in android and iOS. Any idea? Thanks

**Comment by cmdrootaccess** [comment]
hello, i will make an example and show you

**Comment by abdulrojak288** [comment]
I am waiting for you

**Comment by abdulrojak288** [comment]
> hello, i will make an example and show you
I am waiting for you

**Comment by sherkot** [comment]
i have same issue. Any news?

**Comment by cmdrootaccess** [comment]
fixed in 1.10.19

**Comment by cmdrootaccess** [comment]
fixed in 1.10.19

**Comment by Nihalcm** [comment]
how its solved?

**Comment by lighthead9288** [comment]
This fix was working in version 1.12.30, but a flushbar has been stopped appear on the top of keyboard since version 1.12.31.
https://www.dropbox.com/scl/fi/q7vdar48v0dnwiovmo8sk/snackbar_behind_keyboard.webm?rlkey=9qy3mkyed4f19k23mfknt8iw1&e=1&st=4ol6osqq&dl=0

@cmdrootaccess May you fix it?
