### ISSUE TITLE
Has Flushbar or not?

### ISSUE THREAD

**Issue by nurassylive** [cmdrootaccess/another-flushbar#28]
Hi everyone, how can I check if there already a Flushbar is? I don't want to show Flashbar above previous Flashbar. It's weird. Thanks in advance!
P.S. In regular SnackBar from Scaffold you can remove current SnackBar:)

**Comment by surister** [comment]
https://github.com/cmdrootaccess/another-flushbar/blob/b55b782d5e319218fef4593bf9d0a1465ab00c2e/lib/flushbar.dart#L284

**Comment by cmdrootaccess** [comment]
fixed in another_flushbar: ^1.10.22
