### ISSUE TITLE
[Question/Bug] leftBarIndicatorColor and borderRadius

### ISSUE THREAD

**Issue by fernando-s97** [cmdrootaccess/another-flushbar#29]
**Describe the bug**

When using leftBarIndicatorColor property alongside borderRadius, the left side doesn't respect the borderRadius property. Is it correct? If so, what about implementing an option to forceBorderRadius?

**Paste relevant code**

```dart
Flushbar(
      message: message,
      icon: const Icon(Icons.warning, color: Colors.red),
      leftBarIndicatorColor: Colors.red,
      duration: _defaultDuration,
      margin: _defaultMargin,
      borderRadius: _defaultBorderRadius,
    ).show(context);
```

**Screenshots**

![image](https://user-images.githubusercontent.com/20338690/117503646-9d3d7c00-af57-11eb-8cde-2029ebe28fc6.png)

**Comment by cmdrootaccess** [comment]
fixed in 1.10.21
![sss](https://user-images.githubusercontent.com/14039016/118254501-d7f16800-b4b3-11eb-857e-e059d554a6dd.jpg)
