### ISSUE TITLE
Stack Alerts

### ISSUE THREAD

**Issue by luis-cruzt** [cmdrootaccess/another-flushbar#3]
Would be nice to implement this, taked from: [original repo](https://github.com/AndreHaueisen/flushbar/issues/98)

I would like the ability to stack alerts on top of each other (appearing at the same time). I see the example with the form, but it would be nice to be able to interact with each item independently. We currently queue them up after each other.

**Comment by luis-cruzt** [comment]
Also, there's a [pull request](https://github.com/AndreHaueisen/flushbar/pull/100) that mentions this issue.

**Comment by cmdrootaccess** [comment]
done. published in version 1.10.9
