### ISSUE TITLE
Move away from pedantic package

### ISSUE THREAD

**Issue by Silver-Fullbuster** [cmdrootaccess/another-flushbar#49]
The [pedantic](https://pub.dev/packages/pedantic) package has been discontinued in favour of [lints](https://pub.dev/packages/lints) and [flutter_lints](https://pub.dev/packages/flutter_lints).

another_flushbar currently depends on `pedantic`. It should be replaced by a currently maintained package

**Comment by Miamoto-Musashi** [comment]
seems fixed on #47 but not yet released, pls release it ;)

**Comment by cmdrootaccess** [comment]
released in another_flushbar: ^1.10.27
