### ISSUE TITLE
Flushbar is hidden behind keyboard

### ISSUE THREAD

**Issue by eggnstone** [cmdrootaccess/another-flushbar#5]
When a Flushbar is shown while the keyboard is open the Flushbar is hidden behind it.
When I use a standard Snackbar instead it is shown above the keyboard.

My expectation is that the Flushbar is shown above the keyboard as well.

Same problem as
https://github.com/AndreHaueisen/flushbar/issues/7

**Comment by EderGuima** [comment]
Same problem here.. I'm using 1.10.17

**Comment by cmdrootaccess** [comment]
are you using in simulator ? if not which device ? so i can debug

**Comment by lemunozm** [comment]
I have the same issue. 

In my case Android emulator version 10 with API 29.

**Comment by EderGuima** [comment]
> are you using in simulator ? if not which device ? so i can debug

I`m using a Samsung Galaxy S10
Android Version 9

**Comment by cmdrootaccess** [comment]
okay i have a similar device. will test shortly

**Comment by EderGuima** [comment]
> okay i have a similar device. will test shortly

I'm new on Flutter. 
There is my code. Is that my fault? 

_listenToLoginErrors() {
  String message;
  _loginErrorSubscription =
      controller.loginErrorOutput.listen((errorMessage) {
        Flushbar(
          title: signInError.i18n,
          message: errorMessage,
          duration: Duration(seconds: 4),
          margin: EdgeInsets.all(16.0),
          padding: EdgeInsets.symmetric(horizontal: 24.0, vertical: 16.0),
          borderRadius: BorderRadius.circular(50),
        )..show(context);
      });
}

**Comment by slvjr** [comment]
Same here. I'm using Android 8 and 10.

**Comment by mono0926** [comment]
@eggnstone @cmdrootaccess 

Degrated at https://github.com/cmdrootaccess/another-flushbar/commit/0eeb74f581181cbee1b5b3e2acb18328fa2c1b54.
<img width="902" alt="image" src="https://user-images.githubusercontent.com/1255062/112919911-ea515580-9142-11eb-994a-0e9a74e03276.png">

**Comment by abdulrojak288** [comment]
Same here. I'm using IOS 6

**Comment by pauli2406** [comment]
Same problem here. Took me a while to understand that my code was not the problem .. :D

**Comment by cmdrootaccess** [comment]
fixed in 1.10.19
