### ISSUE TITLE
Wait for current showing flushbar to hide before showing a new one

### ISSUE THREAD

**Issue by RobinLbt** [cmdrootaccess/another-flushbar#54]
I would like to have a flushbar one at a time so that flushbar B waits for flushbar A to hide

Is this even possible?

**Comment by Varsius** [comment]
Hey, I had the same problem and after trying for bit I think I have got a working solution using the onStatusChanged parameter:


    Flushbar(
        duration: Duration(seconds: 3),  
        title: 'Title',  
        message: 'Message',  
        onStatusChanged: (FlushbarStatus? status) {  
          if (status == FlushbarStatus.DISMISSED) {  
            showFlushbarB();  
          }
        },
      ).show(context);

**Comment by cmdrootaccess** [comment]
closing. solution provided
