### ISSUE TITLE
Flutter 3 Upgrade

### ISSUE THREAD

**Issue by beaurepair** [cmdrootaccess/another-flushbar#65]
Package is incompatible with Flutter 3's changes to null-aware operations.

../../Library/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/another_flushbar-1.10.28/lib/flushbar.dart:350:22: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
[        ]  - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../Library/Flutter/flutter/packages/flutter/lib/src/scheduler/binding.dart').
[        ]     SchedulerBinding.instance!.addPostFrameCallback(

**Comment by RichardGuesso** [comment]
I have this problem too. In Flutter 3.0
![image](https://user-images.githubusercontent.com/65194302/168077887-a8b399ee-3ef7-49df-b51b-522ff179e925.png)

I removed the question mark in the flushbar.dart class and the error is gone. Hope the team fixes it.
![image](https://user-images.githubusercontent.com/65194302/168078300-e1a0fac5-f102-4db3-be9c-b2dafba345ab.png)
![image](https://user-images.githubusercontent.com/65194302/168078414-aca5fce2-04d8-4376-a48b-4a143527b19c.png)

is that with the new version of flutter now the instance cannot come nulla anymore. This is just a warning.

**Comment by X-SLAYER** [comment]
i made a PR that resolve this [pull#66](https://github.com/cmdrootaccess/another-flushbar/pull/66#issue-1233584993) 

you can use this until the next update
```yaml
another_flushbar:
  git:
    url: git@github.com:X-SLAYER/another-flushbar.git
```

**Comment by panuplanet** [comment]
![image](https://user-images.githubusercontent.com/102588602/168416067-b7f2392d-86e7-4b5f-a0f8-9e44938a32f8.png)


Why can't I use it?

**Comment by X-SLAYER** [comment]
use https like that 

```yaml
another_flushbar:
  git:
    url: https://github.com/X-SLAYER/another-flushbar.git
```

**Comment by labaxter** [comment]
This is affecting  me too. Creating comment to (hopefully) get notified when this is fixed.

**Comment by RoyalCoder88** [comment]
same problem here

**Comment by Jake-Duncan** [comment]
I also am seeing this issue.

**Comment by Jake-Duncan** [comment]
For what its worth, this doesn't appear to be causing any issues in functionality, though I am seeing the same warning message. I just tested in iOS and android and I am seeing the Flushbars appear as expected.

**Comment by cmdrootaccess** [comment]
this is addressed in main branch

**Comment by stayallive** [comment]
Thanks @X-SLAYER and @cmdrootaccess 💪
