### ISSUE TITLE
Problem to run the app, because of null check

### ISSUE THREAD

**Issue by Arlindo-Pelembe-Jr** [cmdrootaccess/another-flushbar#68]
Hi, we are facing difficult to iniatialize the because of one line or something relad the bus is: 

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/another_flushbar-1.10.29/lib/flushbar.dart:350:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback(
                              ^^^^^^^^^^^^^^^^^^^^
                              
                              
                              
                              FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by moNiti** [comment]
same here

**Comment by lordlamee** [comment]
same issue here

**Comment by PlugFox** [comment]
Same

**Comment by bdaniel-moovency** [comment]
I have encountered the same issue, going back to version 1.10.28 fixed it for now.

**Comment by saurabhkumar8112** [comment]
I think the author can keep this version as v2 based on semantic versioning practices : https://semver.org/

**Comment by singhtaranjeet** [comment]
For now you can use version **1.10.27** but this should be resolved by the author.

**Comment by floxydio** [comment]
Already Fixed, But wait for author accept this [https://github.com/cmdrootaccess/another-flushbar/pull/69](url)

**Comment by raudyagdel** [comment]
Same error, hope PR is accepted soon

**Comment by cmdrootaccess** [comment]
addressed in https://github.com/cmdrootaccess/another-flushbar/issues/81
