### ISSUE TITLE
What Version that i can use, with no error ?

### ISSUE THREAD

**Issue by MartinDewe** [cmdrootaccess/another-flushbar#72]
Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.
    SchedulerBinding.instance.addPostFrameCallback(
                              ^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

==================================

another_flushbar: ^1.10.27 ( I tried using this, but same )

**Comment by raudyagdel** [comment]
Any suggestion to solve this error?

**Comment by floxydio** [comment]
im still waiting creator to approve my pull request, maybe you can downgrade to 1.10.28
