### ISSUE TITLE
Expected value of SkDeletable, but got one of type Null

### ISSUE THREAD

**Issue by coastalgit** [cmdrootaccess/another-flushbar#8]
Running release 1.10.11, after upgrading project to Flutter 2, I am seeing an error (on **Flutter WEB** only) whereby when a flushbar is showing when a route is pushed, I am encountering an error:

The following TypeErrorImpl was thrown building FutureBuilder<Size>(dirty, state: _FutureBuilderState<Size>#0334f):
Expected a value of type 'SkDeletable', but got one of type 'Null'

```
The relevant error-causing widget was: 
  Flushbar<dynamic> file:/// {project path to page} /login_page.dart:513:14
When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 84:3    castError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 266:34   as
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart 146:55    new
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/image_filter.dart 26:3           __
```

**Comment by cmdrootaccess** [comment]
noted. will look into it and push new version.

**Comment by cmdrootaccess** [comment]
@coastalgit please try the new version. 1.10.12

**Comment by cmdrootaccess** [comment]
fixed in 1.10.13

**Comment by deakjahn** [comment]
@cmdrootaccess Sorry, but still there in 1.10.17.

**Comment by cmdrootaccess** [comment]
@deakjahn hmm , will investigate.  is t happening in web also ?

**Comment by deakjahn** [comment]
Only in web.

**Comment by Ayush-Suman** [comment]
Expected a value of type 'SkDeletable', but got one of type 'Null'
Using library flutter_svg_provider: ^0.1.9 for loading SVG images into Flutter Web. Working fine for mobile devices.

**Comment by cmdrootaccess** [comment]
just tested in flutter web with another_flushbar: ^1.10.21 . i have noticed such issue

**Comment by deakjahn** [comment]
Maybe you don't but I still do, sorry. :-))

![Screenshot 2021-05-14 135919](https://user-images.githubusercontent.com/2234271/118267603-a335de80-b4bc-11eb-8c9a-d2eeeda12050.png)

**Comment by deakjahn** [comment]
Maybe you don't, but I still do. Sorry... :-))

![Screenshot 2021-05-14 135919](https://user-images.githubusercontent.com/2234271/118267798-e1cb9900-b4bc-11eb-94c6-f7bd608ceb90.png)

**Comment by cmdrootaccess** [comment]
whats your flutter version ?

**Comment by deakjahn** [comment]
The latest and greatest, Flutter 2.3.0-1.0.pre • channel dev.

**Comment by cmdrootaccess** [comment]
This runs on my pc. 
```
Flutter 2.0.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1d9032c7e1 (2 weeks ago) • 2021-04-29 17:37:58 -0700
Engine • revision 05e680e202
Tools • Dart 2.12.3
```
[Uploading Archive.zip…]()

**Comment by deakjahn** [comment]
Sadly, if you need to get access to fixes that are long done in Flutter but will take a year or so to arrive at the stable, you also need to check with 'dev'. And if you do Flutter Web work, even more. :-)
