### ISSUE TITLE
Ftutter v2.8.1

### ISSUE THREAD

**Issue by Savdancode** [cmdrootaccess/another-flushbar#84]
I got this error on my exist project can you help to fix it?

../../../Dev/flutter/.pub-cache/hosted/pub.dartlang.org/another_flushbar-1.12.29/lib/flushbar.dart:350:31: Error: Method 'addPostFrameCallback' cannot be called on 'SchedulerBinding?' because it is potentially null.
 - 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('../../../Dev/flutter/packages/flutter/lib/src/scheduler/binding.dart').
Try calling using ?. instead.

**Comment by cmdrootaccess** [comment]
https://github.com/cmdrootaccess/another-flushbar/issues/81
